### ISSUE TITLE
Failed to initialize the window record because the default font for DrawText, Geneva, was not found.

### ISSUE THREAD

**Issue by montyhugh** [Psychtoolbox-3/Psychtoolbox-3#337]
Running a simple experiment with Psychtoolbox that used to work with my 2014 version of MATLAB and now I can't even open a window because I get the error in the title: "Failed to initialize the window record because the default font for DrawText, Geneva, was not found." I'm not super experienced with MATLAB or with Psychtoolbox so I have no idea how to go about fixing this.

**Comment by kleinerm** [comment]
OSX versions older than 10.11 El Crapitan are no longer officially supported and i don't test against them anymore. Assuming you use the latest El Crapitan, and latest PTB beta from the v3.0.12 series, make sure to read "help DrawTextPlugin" for potential troubleshooting instructions. There are no other known problems with text rendering on OSX that aren't fixed by reading those instructions.

Otherwise post the full output of PTB.

Btw. Geneva is no longer the default font on current PTB betas, "Arial" is. So that points to you using an outdated and unsupported version of PTB.

**Comment by montyhugh** [comment]
I am using the latest version of El Capitan and I installed and reinstalled Psychtoolbox twice. The issue oddly happens when I try to 'OpenWindow'; however, I followed the recommendations in "help DrawTextPlugin" and I still have the same issue.

**Comment by kleinerm** [comment]
Ok, that Geneva in the error message is misleading - a hardcoded text string. It is probably trying to get Arial. Screen('Preference','DefaultFontName') would tell you and it should be Arial. Screen('Preference','DefaultFontStyle') should be zero.

So font enumeration somehow fails. Maybe your OSX font database is damaged, or missing this font. Use the "FontBook" app (or something called like that) to check for existence of that font and possibly repair the font database. It's certainly not a PTB bug causing this, but some damage to your OSX installation.

**Comment by montyhugh** [comment]
I figured it out. Thanks for your help. Oddly, it looks like installing OSX Yosemite uninstalls Arial, or my computer somehow uninstalled it. Installing it again fixes Psychtoolbox.

**Comment by activatedvoxel** [comment]
Arial was actually disabled on my brand new computer with Sierra.  I had to use the font book to enable it.
